// package
// This class was generated by MaxQ (maxq.tigris.org)
package org.dbforms.bookstore;

// definition of test class
public class TestIsWebEvent extends AbstractTestBase {
	// Test method generated from the MaxQ Java generator
	public TestIsWebEvent(String name) {
		super(name);
	}
	public void testTestIsWebEvent() throws Exception {
		System.out.println(
			"Testing URL: "
				+ replaceURL("http://localhost/bookstore/tests/testIsWebEvent.jsp"));
		get("http://localhost/bookstore/tests/testIsWebEvent.jsp");
		System.out.println("Response code: " + getResponse().getStatusCode());
		assertEquals(
			"Assert number 1 failed",
			200,
			getResponse().getStatusCode());
		printResponse();
		assertTrue(responseContains("Hijacking through the Galaxy 6"));
		assertTrue(responseContains("this should be printed"));
		assertTrue(responseContains("this should also be printed"));
		assertFalse(responseContains("this should not be printed"));

	}

	/****************/

}
