// package
// This class was generated by MaxQ (maxq.tigris.org)
package org.dbforms.bookstore;

// imports
import java.util.List;
import java.util.ArrayList;
import java.util.Locale;

import HTTPClient.NVPair;


import org.dbforms.util.MessageResourcesInternal;
import org.dbforms.util.MessageResources;

// definition of test class
public class TestSearch extends AbstractTestBase {
   private static String nodata = null;       

   // Test method generated from the MaxQ Java generator
   public TestSearch(String name) {
      super(name);
      if (nodata == null) {
         MessageResources.setSubClass("resources");
         nodata = MessageResourcesInternal.getMessage("dbforms.nodata", Locale.getDefault());
      }
   }

   public void testSearching() throws Exception {
      List list;

      System.out.println("Testing URL: " + replaceURL("http://localhost/bookstore/tests/testSEARCH.jsp"));
      get("http://localhost/bookstore/tests/testSEARCH.jsp");
      System.out.println("Response code: " + getResponse().getStatusCode());
      assertEquals("Assert number 1 failed", 200, getResponse().getStatusCode());
      printResponse();
      assertTrue(responseContains("<h1>Search Page</h1>"));

      list = new ArrayList();
      list.add(new NVPair("invtable", "1"));
      list.add(new NVPair("invname_1", ""));
      list.add(new NVPair("autoupdate_1", "false"));
      list.add(new NVPair("fu_1", "/tests/testSEARCHRESULTS.jsp"));
      list.add(new NVPair("source", "/bookstore/tests/testSEARCH.jsp"));
      list.add(new NVPair("customEvent", ""));
      list.add(new NVPair("firstpos_1", "0%3A1%3A1-2%3A1%3A1"));
      list.add(new NVPair("lastpos_1", "0%3A1%3A9-2%3A1%3A2"));
      list.add(new NVPair("dataac_goto_1_8_fu", "/tests/testSEARCHRESULTS.jsp"));
      list.add(new NVPair("dataac_goto_1_8_singleRow", "false"));
      list.add(new NVPair("search_1_3", "Hij%"));
      list.add(new NVPair("searchalgo_1_3", "weak"));
      list.add(new NVPair("k_1_0@root", "0%3A1%3A1-2%3A1%3A1"));
      list.add(new NVPair("k_1_1@root", "0%3A1%3A2-2%3A1%3A1"));
      list.add(new NVPair("k_1_2@root", "0%3A1%3A3-2%3A1%3A2"));
      list.add(new NVPair("k_1_3@root", "0%3A1%3A4-2%3A1%3A2"));
      list.add(new NVPair("k_1_4@root", "0%3A1%3A5-2%3A1%3A2"));
      list.add(new NVPair("k_1_5@root", "0%3A1%3A6-2%3A1%3A2"));
      list.add(new NVPair("k_1_6@root", "0%3A1%3A7-2%3A0%3A"));
      list.add(new NVPair("k_1_7@root", "0%3A1%3A8-2%3A1%3A2"));
      list.add(new NVPair("k_1_8@root", "0%3A1%3A9-2%3A1%3A2"));
      System.out.println(
         "Testing URL: "
            + replaceURL("http://localhost/bookstore/servlet/control?invtable=1&invname_1=&autoupdate_1=false&fu_1=/tests/testSEARCHRESULTS.jsp&source=/bookstore/tests/testSEARCH.jsp&customEvent=&firstpos_1=0%3A1%3A1-2%3A1%3A1&lastpos_1=0%3A1%3A9-2%3A1%3A2&dataac_goto_1_8_fu=/tests/testSEARCHRESULTS.jsp&dataac_goto_1_8_singleRow=false&search_1_3=Hij%&searchalgo_1_3=weak&k_1_0@root=0%3A1%3A1-2%3A1%3A1&k_1_1@root=0%3A1%3A2-2%3A1%3A1&k_1_2@root=0%3A1%3A3-2%3A1%3A2&k_1_3@root=0%3A1%3A4-2%3A1%3A2&k_1_4@root=0%3A1%3A5-2%3A1%3A2&k_1_5@root=0%3A1%3A6-2%3A1%3A2&k_1_6@root=0%3A1%3A7-2%3A0%3A&k_1_7@root=0%3A1%3A8-2%3A1%3A2&k_1_8@root=0%3A1%3A9-2%3A1%3A2"));
      post("http://localhost/bookstore/servlet/control", list);
      System.out.println("Response code: " + getResponse().getStatusCode());
      assertEquals("Assert number 2 failed", 200, getResponse().getStatusCode());
      printResponse();
      assertTrue(responseContains("<h1>Search Page</h1>"));
      
      
      list = new ArrayList();
      list.add(new NVPair("invtable", "1"));
      list.add(new NVPair("invname_1", ""));
      list.add(new NVPair("autoupdate_1", "false"));
      list.add(new NVPair("fu_1", "/tests/testSEARCHRESULTS.jsp"));
      list.add(new NVPair("source", "/bookstore/tests/testSEARCH.jsp"));
      list.add(new NVPair("customEvent", ""));
      list.add(new NVPair("firstpos_1", "0%3A1%3A3-2%3A1%3A2"));
      list.add(new NVPair("lastpos_1", "0%3A1%3A9-2%3A1%3A2"));
      list.add(new NVPair("dataac_goto_1_9_fu", "/tests/testSEARCHRESULTS.jsp"));
      list.add(new NVPair("dataac_goto_1_9_singleRow", "false"));
      list.add(new NVPair("ac_goto_1_9", "Search!"));
      list.add(new NVPair("search_1_3", "Hij%"));
      list.add(new NVPair("k_1_0@root", "0%3A1%3A3-2%3A1%3A2"));
      list.add(new NVPair("k_1_1@root", "0%3A1%3A4-2%3A1%3A2"));
      list.add(new NVPair("k_1_2@root", "0%3A1%3A5-2%3A1%3A2"));
      list.add(new NVPair("k_1_3@root", "0%3A1%3A6-2%3A1%3A2"));
      list.add(new NVPair("k_1_4@root", "0%3A1%3A9-2%3A1%3A2"));
      System.out.println(
         "Testing URL: "
            + replaceURL("http://localhost/bookstore/servlet/control?invtable=1&invname_1=&autoupdate_1=false&fu_1=/tests/testSEARCHRESULTS.jsp&source=/bookstore/tests/testSEARCH.jsp&customEvent=&firstpos_1=0%3A1%3A3-2%3A1%3A2&lastpos_1=0%3A1%3A9-2%3A1%3A2&dataac_goto_1_9_fu=/tests/testSEARCHRESULTS.jsp&dataac_goto_1_9_singleRow=false&ac_goto_1_9=Search!&search_1_3=Hij%&k_1_0@root=0%3A1%3A3-2%3A1%3A2&k_1_1@root=0%3A1%3A4-2%3A1%3A2&k_1_2@root=0%3A1%3A5-2%3A1%3A2&k_1_3@root=0%3A1%3A6-2%3A1%3A2&k_1_4@root=0%3A1%3A9-2%3A1%3A2"));
      post("http://localhost/bookstore/servlet/control", list);
      System.out.println("Response code: " + getResponse().getStatusCode());
      assertEquals("Assert number 3 failed", 200, getResponse().getStatusCode());
      printResponse();
      assertTrue(responseContains(nodata));
      

      list = new ArrayList();
      list.add(new NVPair("invtable", "1"));
      list.add(new NVPair("invname_1", ""));
      list.add(new NVPair("autoupdate_1", "false"));
      list.add(new NVPair("fu_1", "/tests/testSEARCHRESULTS.jsp"));
      list.add(new NVPair("source", "/bookstore/tests/testSEARCH.jsp"));
      list.add(new NVPair("customEvent", ""));
      list.add(new NVPair("firstpos_1", "0%3A1%3A3-2%3A1%3A2"));
      list.add(new NVPair("lastpos_1", "0%3A1%3A9-2%3A1%3A2"));
      list.add(new NVPair("dataac_goto_1_9_fu", "/tests/testSEARCHRESULTS.jsp"));
      list.add(new NVPair("dataac_goto_1_9_singleRow", "false"));
      list.add(new NVPair("ac_goto_1_9", "Search!"));
      list.add(new NVPair("search_1_3", "Hij%"));
      list.add(new NVPair("searchalgo_1_3", "weak"));
      list.add(new NVPair("k_1_0@root", "0%3A1%3A3-2%3A1%3A2"));
      list.add(new NVPair("k_1_1@root", "0%3A1%3A4-2%3A1%3A2"));
      list.add(new NVPair("k_1_2@root", "0%3A1%3A5-2%3A1%3A2"));
      list.add(new NVPair("k_1_3@root", "0%3A1%3A6-2%3A1%3A2"));
      list.add(new NVPair("k_1_4@root", "0%3A1%3A9-2%3A1%3A2"));
      System.out.println(
         "Testing URL: "
            + replaceURL("http://localhost/bookstore/servlet/control?invtable=1&invname_1=&autoupdate_1=false&fu_1=/tests/testSEARCHRESULTS.jsp&source=/bookstore/tests/testSEARCH.jsp&customEvent=&firstpos_1=0%3A1%3A3-2%3A1%3A2&lastpos_1=0%3A1%3A9-2%3A1%3A2&dataac_goto_1_9_fu=/tests/testSEARCHRESULTS.jsp&dataac_goto_1_9_singleRow=false&ac_goto_1_9=Search!&search_1_3=Hij%&searchalgo_1_3=weak&k_1_0@root=0%3A1%3A3-2%3A1%3A2&k_1_1@root=0%3A1%3A4-2%3A1%3A2&k_1_2@root=0%3A1%3A5-2%3A1%3A2&k_1_3@root=0%3A1%3A6-2%3A1%3A2&k_1_4@root=0%3A1%3A9-2%3A1%3A2"));
      post("http://localhost/bookstore/servlet/control", list);
      System.out.println("Response code: " + getResponse().getStatusCode());
      assertEquals("Assert number 4 failed", 200, getResponse().getStatusCode());
      printResponse();
      assertTrue(responseContains("Hijacking through the Galaxy 1"));
      assertTrue(responseContains("Hijacking through the Galaxy 2"));
      assertTrue(responseContains("Hijacking through the Galaxy 3"));
      assertTrue(responseContains("Hijacking through the Galaxy 4"));
      assertTrue(responseContains("Hijacking through the Galaxy 6"));

   }

}
