// package
// This class was generated by MaxQ (maxq.tigris.org)
package org.dbforms.bookstore;

import org.dbforms.util.HttpTestCase;

// definition of test class
public class TestGetDBConnection extends HttpTestCase {
	// Test method generated from the MaxQ Java generator
	public TestGetDBConnection(String name) {
		super(name);
	}

	public void testGetDBConnection() throws Exception {
		get("http://localhost/bookstore/tests/testGetDBConnection.jsp");

		printResponse();
		assertTrue(responseContains("Die Insel des vorigen Tages"));
		assertTrue(responseContains("Das Foucaltsche Pendel"));
		assertTrue(responseContains("Hijacking through the Galaxy 1"));
		assertTrue(responseContains("Hijacking through the Galaxy 2"));
		assertTrue(responseContains("Hijacking through the Galaxy 3"));
		assertTrue(responseContains("Hijacking through the Galaxy 4"));
		assertTrue(responseContains("Test null value"));
		assertTrue(responseContains("Luca&#039;s favorite thing to eat is  &#034;delicious Italian pasta&#034;"));
		assertTrue(responseContains("Hijacking through the Galaxy 6"));

	}

	/** ************* */

}
