// package
// This class was generated by MaxQ (maxq.tigris.org)
package org.dbforms.bookstore;

import org.dbforms.util.HttpTestCase;

// definition of test class
public class TestIsWebEvent extends HttpTestCase {
	// Test method generated from the MaxQ Java generator
	public TestIsWebEvent(String name) {
		super(name);
	}

	public void testTestIsWebEvent() throws Exception {
		get("http://localhost/bookstore/tests/testIsWebEvent.jsp");
		printResponse();
		assertTrue(responseContains("Hijacking through the Galaxy 6"));
		assertTrue(responseContains("this should be printed"));
		assertTrue(responseContains("this should also be printed"));
		assertFalse(responseContains("this should not be printed"));

	}

	/** ************* */

}
