// package
// This class was generated by MaxQ (maxq.tigris.org)
package org.dbforms.bookstore;
// imports
import java.util.List;
import java.util.ArrayList;

import java.util.Locale;

import org.dbforms.util.HttpTestCase;
import org.dbforms.util.MessageResourcesInternal;
import org.dbforms.util.MessageResources;

import org.dbforms.util.KeyValuePair;

// definition of test class
public class TestAuthorBooksSubForm extends HttpTestCase
{
   private static String nodata = null;       

	// Test method generated from the MaxQ Java generator
	public TestAuthorBooksSubForm(String name)
	{
      super(name);
      if (nodata == null) {
         MessageResources.setSubClass("resources");
         nodata = MessageResourcesInternal.getMessage("dbforms.nodata", Locale.getDefault());
      }
	}

	/**
	 * Start the tests.
	 *
	 * @param theArgs the arguments. Not used
	 */
	public static void main(String[] theArgs)
	{
		junit.textui.TestRunner.main(new String[] { TestAuthorBooksSubForm.class.getName()});
	}

	public void testNavNewMain() throws Exception
	{
		List list;

		get("http://localhost/bookstore/tests/testAuthorBooksSubForm.jsp");
		printResponse();

		list = new ArrayList();
		list.add(new KeyValuePair("invtable", "0"));
		list.add(new KeyValuePair("invname_0", "null"));
		list.add(new KeyValuePair("autoupdate_0", "false"));
		list.add(new KeyValuePair("fu_0", "/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("source", "/bookstore/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("customEvent", ""));
		list.add(new KeyValuePair("firstpos_0", "0%3A1%3A1-1%3A12%3AEco%2C+Umberto-2%3A15%3Aorganisation+11"));
		list.add(new KeyValuePair("lastpos_0", "0%3A1%3A1-1%3A12%3AEco%2C+Umberto-2%3A15%3Aorganisation+11"));
		list.add(new KeyValuePair("f_0_0@root_1", "Eco, Umberto"));
		list.add(new KeyValuePair("f_0_0@root_2", "organisation 11"));
		list.add(new KeyValuePair("ac_next_0", ">  Next"));
		list.add(new KeyValuePair("invtable", "1"));
		list.add(new KeyValuePair("invname_1", "null"));
		list.add(new KeyValuePair("autoupdate_1", "false"));
		list.add(new KeyValuePair("fu_1", "/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("source", "/bookstore/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("customEvent", ""));
		list.add(new KeyValuePair("firstpos_1", "0%3A1%3A1-2%3A1%3A1-3%3A27%3ADie+Insel+des+vorigen+Tages"));
		list.add(new KeyValuePair("lastpos_1", "0%3A1%3A2-2%3A1%3A1-3%3A22%3ADas+Foucaltsche+Pendel"));
		list.add(new KeyValuePair("f_1_0@0@root_1", "3-423-12445-4"));
		list.add(new KeyValuePair("f_1_0@0@root_3", "Die Insel des vorigen Tages"));
		list.add(new KeyValuePair("f_1_1@0@root_1", "3-423-12445-5"));
		list.add(new KeyValuePair("f_1_1@0@root_3", "Das Foucaltsche Pendel"));
		list.add(new KeyValuePair("k_1_0@0@root", "0%3A1%3A1-2%3A1%3A1-3%3A27%3ADie+Insel+des+vorigen+Tages"));
		list.add(new KeyValuePair("f_1_ins0@root_2", "1"));
		list.add(new KeyValuePair("k_1_1@0@root", "0%3A1%3A2-2%3A1%3A1-3%3A22%3ADas+Foucaltsche+Pendel"));
		list.add(new KeyValuePair("f_1_ins0@root_2", "1"));
		list.add(new KeyValuePair("k_0_0@root", "0%3A1%3A1"));
		post("http://localhost/bookstore/servlet/control", list);
		printResponse();

		list = new ArrayList();
		list.add(new KeyValuePair("invtable", "0"));
		list.add(new KeyValuePair("invname_0", "null"));
		list.add(new KeyValuePair("autoupdate_0", "false"));
		list.add(new KeyValuePair("fu_0", "/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("source", "/bookstore/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("customEvent", ""));
		list.add(new KeyValuePair("firstpos_0", "0%3A1%3A2-1%3A13%3ADouglas%2C+Adam-2%3A14%3Aorganisation+2"));
		list.add(new KeyValuePair("lastpos_0", "0%3A1%3A2-1%3A13%3ADouglas%2C+Adam-2%3A14%3Aorganisation+2"));
		list.add(new KeyValuePair("f_0_0@root_1", "Douglas, Adam"));
		list.add(new KeyValuePair("f_0_0@root_2", "organisation 2"));
		list.add(new KeyValuePair("ac_next_0", ">  Next"));
		list.add(new KeyValuePair("invtable", "1"));
		list.add(new KeyValuePair("invname_1", "null"));
		list.add(new KeyValuePair("autoupdate_1", "false"));
		list.add(new KeyValuePair("fu_1", "/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("source", "/bookstore/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("customEvent", ""));
		list.add(new KeyValuePair("firstpos_1", "0%3A1%3A3-2%3A1%3A2-3%3A30%3AHijacking+through+the+Galaxy+1"));
		list.add(new KeyValuePair("lastpos_1", "0%3A1%3A9-2%3A1%3A2-3%3A30%3AHijacking+through+the+Galaxy+6"));
		list.add(new KeyValuePair("f_1_0@0@root_1", "42-1"));
		list.add(new KeyValuePair("f_1_0@0@root_3", "Hijacking through the Galaxy 1"));
		list.add(new KeyValuePair("f_1_1@0@root_1", "42-2"));
		list.add(new KeyValuePair("f_1_1@0@root_3", "Hijacking through the Galaxy 2"));
		list.add(new KeyValuePair("f_1_2@0@root_1", "42-3"));
		list.add(new KeyValuePair("f_1_2@0@root_3", "Hijacking through the Galaxy 3"));
		list.add(new KeyValuePair("f_1_3@0@root_1", "42-4"));
		list.add(new KeyValuePair("f_1_3@0@root_3", "Hijacking through the Galaxy 4"));
		list.add(new KeyValuePair("f_1_4@0@root_1", "42-5"));
		list.add(new KeyValuePair("f_1_4@0@root_3", "Luca\'s favorite thing to eat is  "));
		list.add(new KeyValuePair("f_1_5@0@root_1", "42-6"));
		list.add(new KeyValuePair("f_1_5@0@root_3", "Hijacking through the Galaxy 6"));
		list.add(new KeyValuePair("k_1_0@0@root", "0%3A1%3A3-2%3A1%3A2-3%3A30%3AHijacking+through+the+Galaxy+1"));
		list.add(new KeyValuePair("f_1_ins0@root_2", "2"));
		list.add(new KeyValuePair("k_1_1@0@root", "0%3A1%3A4-2%3A1%3A2-3%3A30%3AHijacking+through+the+Galaxy+2"));
		list.add(new KeyValuePair("f_1_ins0@root_2", "2"));
		list.add(new KeyValuePair("k_1_2@0@root", "0%3A1%3A5-2%3A1%3A2-3%3A30%3AHijacking+through+the+Galaxy+3"));
		list.add(new KeyValuePair("f_1_ins0@root_2", "2"));
		list.add(new KeyValuePair("k_1_3@0@root", "0%3A1%3A6-2%3A1%3A2-3%3A30%3AHijacking+through+the+Galaxy+4"));
		list.add(new KeyValuePair("f_1_ins0@root_2", "2"));
		list.add(
			new KeyValuePair(
				"k_1_4@0@root",
				"0%3A1%3A8-2%3A1%3A2-3%3A58%3ALuca%27s+favorite+thing+to+eat+is++%22delicious+Italian+pasta%22"));
		list.add(new KeyValuePair("f_1_ins0@root_2", "2"));
		list.add(new KeyValuePair("k_1_5@0@root", "0%3A1%3A9-2%3A1%3A2-3%3A30%3AHijacking+through+the+Galaxy+6"));
		list.add(new KeyValuePair("f_1_ins0@root_2", "2"));
		list.add(new KeyValuePair("k_0_0@root", "0%3A1%3A2"));
		post("http://localhost/bookstore/servlet/control", list);
		printResponse();
		assertTrue(responseContains("<input type=\"submit\"  value=\"New\"  style=\"width:100\" name=\"ac_new_0"));
		assertTrue(responseContains("<input type=\"submit\"  value=\"Copy\"  style=\"width:100\" name=\"ac_copy_0"));

		list = new ArrayList();
		list.add(new KeyValuePair("invtable", "0"));
		list.add(new KeyValuePair("invname_0", "null"));
		list.add(new KeyValuePair("autoupdate_0", "false"));
		list.add(new KeyValuePair("fu_0", "/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("source", "/bookstore/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("customEvent", ""));
		list.add(new KeyValuePair("firstpos_0", "0%3A1%3A2-1%3A13%3ADouglas%2C+Adam-2%3A14%3Aorganisation+2"));
		list.add(new KeyValuePair("lastpos_0", "0%3A1%3A2-1%3A13%3ADouglas%2C+Adam-2%3A14%3Aorganisation+2"));
		list.add(new KeyValuePair("f_0_0@root_1", "Douglas, Adam"));
		list.add(new KeyValuePair("f_0_0@root_2", "organisation 2"));
		list.add(new KeyValuePair("ac_new_0", "New"));
		list.add(new KeyValuePair("invtable", "1"));
		list.add(new KeyValuePair("invname_1", "null"));
		list.add(new KeyValuePair("autoupdate_1", "false"));
		list.add(new KeyValuePair("fu_1", "/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("source", "/bookstore/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("customEvent", ""));
		list.add(new KeyValuePair("firstpos_1", "0%3A1%3A3-2%3A1%3A2-3%3A30%3AHijacking+through+the+Galaxy+1"));
		list.add(new KeyValuePair("lastpos_1", "0%3A1%3A9-2%3A1%3A2-3%3A30%3AHijacking+through+the+Galaxy+6"));
		list.add(new KeyValuePair("f_1_0@0@root_1", "42-1"));
		list.add(new KeyValuePair("f_1_0@0@root_3", "Hijacking through the Galaxy 1"));
		list.add(new KeyValuePair("f_1_1@0@root_1", "42-2"));
		list.add(new KeyValuePair("f_1_1@0@root_3", "Hijacking through the Galaxy 2"));
		list.add(new KeyValuePair("f_1_2@0@root_1", "42-3"));
		list.add(new KeyValuePair("f_1_2@0@root_3", "Hijacking through the Galaxy 3"));
		list.add(new KeyValuePair("f_1_3@0@root_1", "42-4"));
		list.add(new KeyValuePair("f_1_3@0@root_3", "Hijacking through the Galaxy 4"));
		list.add(new KeyValuePair("f_1_4@0@root_1", "42-5"));
		list.add(new KeyValuePair("f_1_4@0@root_3", "Luca\'s favorite thing to eat is  "));
		list.add(new KeyValuePair("f_1_5@0@root_1", "42-6"));
		list.add(new KeyValuePair("f_1_5@0@root_3", "Hijacking through the Galaxy 6"));
		list.add(new KeyValuePair("k_1_0@0@root", "0%3A1%3A3-2%3A1%3A2-3%3A30%3AHijacking+through+the+Galaxy+1"));
		list.add(new KeyValuePair("f_1_ins0@root_2", "2"));
		list.add(new KeyValuePair("k_1_1@0@root", "0%3A1%3A4-2%3A1%3A2-3%3A30%3AHijacking+through+the+Galaxy+2"));
		list.add(new KeyValuePair("f_1_ins0@root_2", "2"));
		list.add(new KeyValuePair("k_1_2@0@root", "0%3A1%3A5-2%3A1%3A2-3%3A30%3AHijacking+through+the+Galaxy+3"));
		list.add(new KeyValuePair("f_1_ins0@root_2", "2"));
		list.add(new KeyValuePair("k_1_3@0@root", "0%3A1%3A6-2%3A1%3A2-3%3A30%3AHijacking+through+the+Galaxy+4"));
		list.add(new KeyValuePair("f_1_ins0@root_2", "2"));
		list.add(
			new KeyValuePair(
				"k_1_4@0@root",
				"0%3A1%3A8-2%3A1%3A2-3%3A58%3ALuca%27s+favorite+thing+to+eat+is++%22delicious+Italian+pasta%22"));
		list.add(new KeyValuePair("f_1_ins0@root_2", "2"));
		list.add(new KeyValuePair("k_1_5@0@root", "0%3A1%3A9-2%3A1%3A2-3%3A30%3AHijacking+through+the+Galaxy+6"));
		list.add(new KeyValuePair("f_1_ins0@root_2", "2"));
		list.add(new KeyValuePair("k_0_0@root", "0%3A1%3A2"));
		post("http://localhost/bookstore/servlet/control", list);
		printResponse();
		assertFalse(responseContains("<input type=\"submit\"  value=\"New\"  style=\"width:100\" name=\"ac_new_0"));
		assertFalse(responseContains("<input type=\"submit\"  value=\"Copy\"  style=\"width:100\" name=\"ac_copy_0"));
		assertTrue(responseContains("<td style=\"width:100px\">" + nodata + "&nbsp;</td>"));
		assertTrue(
			responseContains("<input type=\"text\" name=\"f_0_insroot_1\" value=\"\"  size=\"25\"/>"));
		assertTrue(responseContains("<input type=\"text\" name=\"f_0_insroot_2\" value=\"\"  size=\"25\"/>"));

	}

	public void testNavCopyMain() throws Exception
	{

		List list;
		get("http://localhost/bookstore/tests/testAuthorBooksSubForm.jsp");
		printResponse();
		assertTrue(responseContains("<input type=\"submit\"  value=\"New\"  style=\"width:100\" name=\"ac_new_0"));
		assertTrue(responseContains("<input type=\"submit\"  value=\"Copy\"  style=\"width:100\" name=\"ac_copy_0"));

		list = new ArrayList();
		list.add(new KeyValuePair("invtable", "0"));
		list.add(new KeyValuePair("invname_0", "null"));
		list.add(new KeyValuePair("autoupdate_0", "false"));
		list.add(new KeyValuePair("fu_0", "/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("source", "/bookstore/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("customEvent", ""));
		list.add(new KeyValuePair("firstpos_0", "0%3A1%3A1-1%3A12%3AEco%2C+Umberto-2%3A15%3Aorganisation+11"));
		list.add(new KeyValuePair("lastpos_0", "0%3A1%3A1-1%3A12%3AEco%2C+Umberto-2%3A15%3Aorganisation+11"));
		list.add(new KeyValuePair("f_0_0@root_1", "Eco, Umberto"));
		list.add(new KeyValuePair("f_0_0@root_2", "organisation 11"));
		list.add(new KeyValuePair("ac_copy_0", "Copy"));
		list.add(new KeyValuePair("invtable", "1"));
		list.add(new KeyValuePair("invname_1", "null"));
		list.add(new KeyValuePair("autoupdate_1", "false"));
		list.add(new KeyValuePair("fu_1", "/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("source", "/bookstore/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("customEvent", ""));
		list.add(new KeyValuePair("firstpos_1", "0%3A1%3A1-2%3A1%3A1-3%3A27%3ADie+Insel+des+vorigen+Tages"));
		list.add(new KeyValuePair("lastpos_1", "0%3A1%3A2-2%3A1%3A1-3%3A22%3ADas+Foucaltsche+Pendel"));
		list.add(new KeyValuePair("f_1_0@0@root_1", "3-423-12445-4"));
		list.add(new KeyValuePair("f_1_0@0@root_3", "Die Insel des vorigen Tages"));
		list.add(new KeyValuePair("f_1_1@0@root_1", "3-423-12445-5"));
		list.add(new KeyValuePair("f_1_1@0@root_3", "Das Foucaltsche Pendel"));
		list.add(new KeyValuePair("k_1_0@0@root", "0%3A1%3A1-2%3A1%3A1-3%3A27%3ADie+Insel+des+vorigen+Tages"));
		list.add(new KeyValuePair("f_1_ins0@root_2", "1"));
		list.add(new KeyValuePair("k_1_1@0@root", "0%3A1%3A2-2%3A1%3A1-3%3A22%3ADas+Foucaltsche+Pendel"));
		list.add(new KeyValuePair("f_1_ins0@root_2", "1"));
		list.add(new KeyValuePair("k_0_0@root", "0%3A1%3A1"));
		post("http://localhost/bookstore/servlet/control", list);
		printResponse();
		assertFalse(responseContains("<input type=\"submit\"  value=\"New\"  style=\"width:100\" name=\"ac_new_0"));
		assertFalse(responseContains("<input type=\"submit\"  value=\"Copy\"  style=\"width:100\" name=\"ac_copy_0"));
		assertTrue(responseContains("<td style=\"width:100px\">" + nodata + "&nbsp;</td>"));
		assertTrue(
			responseContains("<input type=\"text\" name=\"f_0_insroot_1\" value=\"Eco, Umberto\"  size=\"25\"/>"));
		assertTrue(responseContains("<input type=\"text\" name=\"f_0_insroot_2\" value=\"organisation 11\"  size=\"25\"/>"));

	}

	public void testNavNewSub() throws Exception
	{
		List list;

		get("http://localhost/bookstore/tests/testAuthorBooksSubForm.jsp");
		printResponse();
		assertTrue(responseContains("<input type=\"submit\"  value=\"New\"  style=\"width:100\" name=\"ac_new_1"));
		assertTrue(responseContains("<input type=\"submit\"  value=\"Copy\"  style=\"width:100\" name=\"ac_copy_1"));

		list = new ArrayList();
		list.add(new KeyValuePair("invtable", "0"));
		list.add(new KeyValuePair("invname_0", "null"));
		list.add(new KeyValuePair("autoupdate_0", "false"));
		list.add(new KeyValuePair("fu_0", "/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("source", "/bookstore/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("customEvent", ""));
		list.add(new KeyValuePair("firstpos_0", "0%3A1%3A1-1%3A12%3AEco%2C+Umberto-2%3A15%3Aorganisation+11"));
		list.add(new KeyValuePair("lastpos_0", "0%3A1%3A1-1%3A12%3AEco%2C+Umberto-2%3A15%3Aorganisation+11"));
		list.add(new KeyValuePair("f_0_0@root_1", "Eco, Umberto"));
		list.add(new KeyValuePair("f_0_0@root_2", "organisation 11"));
		list.add(new KeyValuePair("invtable", "1"));
		list.add(new KeyValuePair("invname_1", "null"));
		list.add(new KeyValuePair("autoupdate_1", "false"));
		list.add(new KeyValuePair("fu_1", "/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("source", "/bookstore/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("customEvent", ""));
		list.add(new KeyValuePair("firstpos_1", "0%3A1%3A1-2%3A1%3A1-3%3A27%3ADie+Insel+des+vorigen+Tages"));
		list.add(new KeyValuePair("lastpos_1", "0%3A1%3A2-2%3A1%3A1-3%3A22%3ADas+Foucaltsche+Pendel"));
		list.add(new KeyValuePair("f_1_0@0@root_1", "3-423-12445-4"));
		list.add(new KeyValuePair("f_1_0@0@root_3", "Die Insel des vorigen Tages"));
		list.add(new KeyValuePair("f_1_1@0@root_1", "3-423-12445-5"));
		list.add(new KeyValuePair("f_1_1@0@root_3", "Das Foucaltsche Pendel"));
		list.add(new KeyValuePair("ac_new_1", "New"));
		list.add(new KeyValuePair("k_1_0@0@root", "0%3A1%3A1-2%3A1%3A1-3%3A27%3ADie+Insel+des+vorigen+Tages"));
		list.add(new KeyValuePair("f_1_ins0@root_2", "1"));
		list.add(new KeyValuePair("k_1_1@0@root", "0%3A1%3A2-2%3A1%3A1-3%3A22%3ADas+Foucaltsche+Pendel"));
		list.add(new KeyValuePair("f_1_ins0@root_2", "1"));
		list.add(new KeyValuePair("k_0_0@root", "0%3A1%3A1"));
		post("http://localhost/bookstore/servlet/control", list);
		printResponse();
		assertTrue(responseContains("<input type=\"submit\"  value=\"New\"  style=\"width:100\" name=\"ac_new_1"));
		assertTrue(responseContains("<input type=\"submit\"  value=\"Copy\"  style=\"width:100\" name=\"ac_copy_1"));

	}

	public void testNavCopySub() throws Exception
	{

		List list;

		get("http://localhost/bookstore/tests/testAuthorBooksSubForm.jsp");
		printResponse();
		assertTrue(responseContains("<input type=\"submit\"  value=\"New\"  style=\"width:100\" name=\"ac_new_1"));
		assertTrue(responseContains("<input type=\"submit\"  value=\"Copy\"  style=\"width:100\" name=\"ac_copy_1"));

		list = new ArrayList();
		list.add(new KeyValuePair("invtable", "0"));
		list.add(new KeyValuePair("invname_0", "null"));
		list.add(new KeyValuePair("autoupdate_0", "false"));
		list.add(new KeyValuePair("fu_0", "/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("source", "/bookstore/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("customEvent", ""));
		list.add(new KeyValuePair("firstpos_0", "0%3A1%3A1-1%3A12%3AEco%2C+Umberto-2%3A15%3Aorganisation+11"));
		list.add(new KeyValuePair("lastpos_0", "0%3A1%3A1-1%3A12%3AEco%2C+Umberto-2%3A15%3Aorganisation+11"));
		list.add(new KeyValuePair("f_0_0@root_1", "Eco, Umberto"));
		list.add(new KeyValuePair("f_0_0@root_2", "organisation 11"));
		list.add(new KeyValuePair("invtable", "1"));
		list.add(new KeyValuePair("invname_1", "null"));
		list.add(new KeyValuePair("autoupdate_1", "false"));
		list.add(new KeyValuePair("fu_1", "/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("source", "/bookstore/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("customEvent", ""));
		list.add(new KeyValuePair("firstpos_1", "0%3A1%3A1-2%3A1%3A1-3%3A27%3ADie+Insel+des+vorigen+Tages"));
		list.add(new KeyValuePair("lastpos_1", "0%3A1%3A2-2%3A1%3A1-3%3A22%3ADas+Foucaltsche+Pendel"));
		list.add(new KeyValuePair("f_1_0@0@root_1", "3-423-12445-4"));
		list.add(new KeyValuePair("f_1_0@0@root_3", "Die Insel des vorigen Tages"));
		list.add(new KeyValuePair("f_1_1@0@root_1", "3-423-12445-5"));
		list.add(new KeyValuePair("f_1_1@0@root_3", "Das Foucaltsche Pendel"));
		list.add(new KeyValuePair("ac_copy_1", "Copy"));
		list.add(new KeyValuePair("k_1_0@0@root", "0%3A1%3A1-2%3A1%3A1-3%3A27%3ADie+Insel+des+vorigen+Tages"));
		list.add(new KeyValuePair("f_1_ins0@root_2", "1"));
		list.add(new KeyValuePair("k_1_1@0@root", "0%3A1%3A2-2%3A1%3A1-3%3A22%3ADas+Foucaltsche+Pendel"));
		list.add(new KeyValuePair("f_1_ins0@root_2", "1"));
		list.add(new KeyValuePair("k_0_0@root", "0%3A1%3A1"));
		post("http://localhost/bookstore/servlet/control", list);
		printResponse();
		assertTrue(responseContains("<td>" + nodata + "&nbsp;</td>"));
		assertTrue(responseContains("<input type=\"text\" name=\"f_1_ins0@root_1\" value=\"3-423-12445-4\" />"));
		assertTrue(responseContains("<input type=\"text\" name=\"f_1_ins0@root_3\" value=\"Die Insel des vorigen Tages\" />"));
		assertTrue(responseContains("<input type=\"submit\"  value=\"New\"  style=\"width:100\" name=\"ac_new_1"));
		assertTrue(responseContains("<input type=\"submit\"  value=\"Copy\"  style=\"width:100\" name=\"ac_copy_1"));

	}

	public void testNavNewInSubForm() throws Exception
	{

		List list;

		get("http://localhost/bookstore/tests/testAuthorBooksSubForm.jsp");
		assertTrue(responseContains("<input type=\"submit\"  value=\"New\"  style=\"width:100\" name=\"ac_new_1"));
		assertTrue(responseContains("<input type=\"submit\"  value=\"Copy\"  style=\"width:100\" name=\"ac_copy_1"));

		list = new ArrayList();
		list.add(new KeyValuePair("invtable", "0"));
		list.add(new KeyValuePair("invname_0", "null"));
		list.add(new KeyValuePair("autoupdate_0", "false"));
		list.add(new KeyValuePair("fu_0", "/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("source", "/bookstore/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("customEvent", ""));
		list.add(new KeyValuePair("firstpos_0", "0%3A1%3A1-1%3A12%3AEco%2C+Umberto-2%3A15%3Aorganisation+11"));
		list.add(new KeyValuePair("lastpos_0", "0%3A1%3A1-1%3A12%3AEco%2C+Umberto-2%3A15%3Aorganisation+11"));
		list.add(new KeyValuePair("f_0_0@root_1", "Eco, Umberto"));
		list.add(new KeyValuePair("f_0_0@root_2", "organisation 11"));
		list.add(new KeyValuePair("invtable", "1"));
		list.add(new KeyValuePair("invname_1", "null"));
		list.add(new KeyValuePair("autoupdate_1", "false"));
		list.add(new KeyValuePair("fu_1", "/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("source", "/bookstore/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("customEvent", ""));
		list.add(new KeyValuePair("firstpos_1", "0%3A1%3A1-2%3A1%3A1-3%3A27%3ADie+Insel+des+vorigen+Tages"));
		list.add(new KeyValuePair("lastpos_1", "0%3A1%3A2-2%3A1%3A1-3%3A22%3ADas+Foucaltsche+Pendel"));
		list.add(new KeyValuePair("f_1_0@0@root_1", "3-423-12445-4"));
		list.add(new KeyValuePair("f_1_0@0@root_3", "Die Insel des vorigen Tages"));
		list.add(new KeyValuePair("f_1_1@0@root_1", "3-423-12445-5"));
		list.add(new KeyValuePair("f_1_1@0@root_3", "Das Foucaltsche Pendel"));
		list.add(new KeyValuePair("ac_new_1", "New"));
		list.add(new KeyValuePair("k_1_0@0@root", "0%3A1%3A1-2%3A1%3A1-3%3A27%3ADie+Insel+des+vorigen+Tages"));
		list.add(new KeyValuePair("f_1_ins0@root_2", "1"));
		list.add(new KeyValuePair("k_1_1@0@root", "0%3A1%3A2-2%3A1%3A1-3%3A22%3ADas+Foucaltsche+Pendel"));
		list.add(new KeyValuePair("f_1_ins0@root_2", "1"));
		list.add(new KeyValuePair("k_0_0@root", "0%3A1%3A1"));
		post("http://localhost/bookstore/servlet/control", list);
		printResponse();
		assertTrue(responseContains("<input type=\"submit\"  value=\"New\"  style=\"width:100\" name=\"ac_new_1"));
		assertTrue(responseContains("<input type=\"submit\"  value=\"Copy\"  style=\"width:100\" name=\"ac_copy_1"));

		list = new ArrayList();
		list.add(new KeyValuePair("invtable", "0"));
		list.add(new KeyValuePair("invname_0", "null"));
		list.add(new KeyValuePair("autoupdate_0", "false"));
		list.add(new KeyValuePair("fu_0", "/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("source", "/bookstore/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("customEvent", ""));
		list.add(new KeyValuePair("firstpos_0", "0%3A1%3A1-1%3A12%3AEco%2C+Umberto-2%3A15%3Aorganisation+11"));
		list.add(new KeyValuePair("lastpos_0", "0%3A1%3A1-1%3A12%3AEco%2C+Umberto-2%3A15%3Aorganisation+11"));
		list.add(new KeyValuePair("f_0_0@root_1", "Eco, Umberto"));
		list.add(new KeyValuePair("f_0_0@root_2", "organisation 11"));
		list.add(new KeyValuePair("ac_next_0", ">  Next"));
		list.add(new KeyValuePair("invtable", "1"));
		list.add(new KeyValuePair("invname_1", "null"));
		list.add(new KeyValuePair("autoupdate_1", "false"));
		list.add(new KeyValuePair("fu_1", "/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("source", "/bookstore/tests/testAuthorBooksSubForm.jsp"));
		list.add(new KeyValuePair("customEvent", ""));
		list.add(new KeyValuePair("f_1_ins0@root_1", ""));
		list.add(new KeyValuePair("f_1_ins0@root_3", ""));
		list.add(new KeyValuePair("k_1_0@0@root", "null"));
		list.add(new KeyValuePair("f_1_ins0@root_2", "1"));
		list.add(new KeyValuePair("k_0_0@root", "0%3A1%3A1"));
		post("http://localhost/bookstore/servlet/control", list);
		printResponse();
		assertTrue(responseContains("<input type=\"text\" name=\"f_0_0@root_1\" value=\"Douglas, Adam\"  size=\"25\"/>"));
		assertTrue(responseContains("<input type=\"text\" name=\"f_1_0@0@root_1\" value=\"42-1\" />"));
	}

}
