// package
// This class was generated by MaxQ (maxq.tigris.org)
package org.dbforms.bookstore;

import org.dbforms.util.HttpTestCase;

// definition of test class
public class TestBOOKSListDynaBug extends HttpTestCase {
    // Test method generated from the MaxQ Java generator
    public TestBOOKSListDynaBug(String name) {
        super(name);
    }
    public void testTest() throws Exception {
        get("http://localhost/bookstore/tests/testBOOKSListDynaBug.jsp");
		printResponse();
		
    }

/****************/

}
